### ISSUE TITLE
你好，如何实现关闭客户端

### ISSUE THREAD

**Issue by jiaoshougao** [dothetrick/binlogportal#2]

**Comment by dothetrick** [comment]
目前的版本里没有获取client的需求，客户端会在程序结束时关闭。
下个版本里会添加获取client的接口，获取后可以调用close方法关闭。

**Comment by dothetrick** [comment]
已提供获取客户端的方法，可通过disconnect()关闭。
d1 = binlogPortalStarter.getClientByDbKey("d1");
d1.disconnect();
